### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by MapperD** [dev7355608/gm-vision#10]
Appears the module has stopped working and I get the message

Error: Error thrown in hooked function '' for hook 'renderSceneControls'. html.querySelector is not a function
[Detected 1 package: gm-vision(2.0.0)]
         at Hooks.onError (foundry.js:654:24)
         at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
         at #call (foundry.js:636:36)
         at Hooks.callAll (foundry.js:589:17)
         at SceneControls._callHooks (foundry.js:5918:13)
         at SceneControls._render (foundry.js:5879:10)
  onError @ foundry.js:655

**Comment by dev7355608** [comment]
GM Vision 2.0.0 is V13 only compatible. Are you running V13 already or did you manage to run 2.0.0 in V12 somehow?

**Comment by MapperD** [comment]
Well darn. So I did...
Usually the module stops you from updating when not compatible so I wasn't
even thinking about that.
Issue solved. Just have to wait now for v13
Thanks

**Comment by dev7355608** [comment]
If you still how you managed to install and run 2.0.0 in V12, it would be good to know. It should be impossible.

**Comment by MapperD** [comment]
I just ran the update all and didn't get any error or message.
I look at it now as just an opps.

I'll just reinstall the previous version until v13 comes out.
